[pytest]

addopts =

    # -----------------------------
    # General Options
    # -----------------------------
    -v
    --browser=chromium
    --headed

    # --base-url=http://localhost/opencart/upload/
    # --base-url=https://tutorialsninja.com/demo/
    # --base-url=https://naveenautomationlabs.com/opencart
    #--base-url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login 
   # --dashboard-url=https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index
    # -----------------------------
    # Captures and Reports (Debugging)
    # -----------------------------
    --video=retain-on-failure
    # --video=on

    --screenshot=only-on-failure
    # --screenshot=on

    --tracing=retain-on-failure
    # --tracing=on

    --html=reports/myreport.html --self-contained-html --capture=tee-sys
    --alluredir=reports/allure-results
